#!/usr/bin/env sh

sudo dnf install \
    texlive-amscls \
    texlive-avantgar \
    texlive-bibtex-bin \
    texlive-bibtex \
    texlive-bigfoot \
    texlive-bookman \
    texlive-charter \
    texlive-cmextra \
    texlive-cm-super \
    texlive-cm \
    texlive-collection-basic \
    texlive-collection-fontsrecommended \
    texlive-courier \
    texlive-dvipdfmx-bin \
    texlive-dvipdfmx-def \
    texlive-dvipdfmx \
    texlive-dvips-bin \
    texlive-dvips \
    texlive-ec \
    texlive-enctex \
    texlive-enumitem \
    texlive-etex \
    texlive-euro \
    texlive-eurosym \
    texlive-fpl \
    texlive-glyphlist \
    texlive-gsftopk-bin \
    texlive-gsftopk \
    texlive-helvetic \
    texlive-hyph-utf8 \
    texlive-ifluatex \
    texlive-latex-bin \
    texlive-lm-math \
    texlive-lua-alt-getopt \
    texlive-makeindex-bin \
    texlive-makeindex \
    texlive-marvosym \
    texlive-mathpazo \
    texlive-metafont-bin \
    texlive-metafont \
    texlive-mflogo \
    texlive-mfware-bin \
    texlive-mfware \
    texlive-ncntrsbk \
    texlive-palatino \
    texlive-pdftex-def \
    texlive-plain \
    texlive-pxfonts \
    texlive-rsfs \
    texlive-symbol \
    texlive-tex-bin \
    texlive-texconfig \
    texlive-tex-gyre-math \
    texlive-tex-gyre \
    texlive-texlive-common-doc \
    texlive-texlive-en-doc \
    texlive-texlive-msg-translations \
    texlive-texlive-scripts-bin \
    texlive-texlive-scripts \
    texlive-tex \
    texlive-textgreek \
    texlive-times \
    texlive-txfonts \
    texlive-utopia \
    texlive-wasy \
    texlive-wasysym \
    texlive-xdvi \
    texlive-zapfchan \
    texlive-zapfding \
